Set-Alias -Name git-checkout -Value Set-GitHead
Set-Alias -Name git-fetch -Value Receive-GitObject
Set-Alias -Name git-pull -Value Receive-GitBranch
Set-Alias -Name git-branch -Value Get-GitBranch
Set-Alias -Name git-reset -Value Reset-GitHead
Set-Alias -Name git-merge -Value Merge-GitCommit
Set-Alias -Name git-push -Value Send-GitBranch
Set-Alias -Name git-add -Value Add-GitItem
Set-Alias -Name git-commit -Value Save-GitCommit
Set-Alias -Name git-rebase -Value Start-GitRebase
Set-Alias -Name git-clone -Value Copy-GitRepository
Set-Alias -Name git-rebase -Value Start-GitRebase
Set-Alias -Name git-rebase-continue -Value Resume-GitRebase
Set-Alias -Name git-rebase-abort -Value Stop-GitRebase
Set-Alias -Name git-remote -Value Get-GitRemote
Set-Alias -Name git-remote-add -Value Add-GitRemote
Set-Alias -Name git-remote-remove -Value Remove-GitRemote
Set-Alias -Name git-remote-rename -Value Rename-GitRemote
